### ISSUE TITLE
Thumbnail (canvas/image) disappears after interacting with filters

### ISSUE THREAD

**Issue by caio1985** [peterpeterparker/web-photo-filter#30]
Hi,

I implemented the solution from https://devdactic.com/ionic-photo-filters-instagram/

Filters are being applied fine to the top image, and the filter thumbnails initially work. But sometimes when I click on the filter thumbnails the image of other filters or even the one I clicked disappears - see image below:

![web-photo-filter-error](https://user-images.githubusercontent.com/1559101/150558603-3475d810-6d41-4d3e-bb63-27db268e949e.jpg)

I also see this on Chrome Dev Tools when I click on a filter:

**`web-photo-filter.entry.js:277 WARNING: Too many active WebGL contexts. Oldest context will be lost.`**

```
Ionic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.3
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.4.0
   @capacitor/android : 3.4.0
   @capacitor/core    : 3.4.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v14.15.1 (/usr/local/bin/node)
   npm    : 8.3.1
   OS     : macOS Monterey
```

Any idea of what could be causing this and how to fix?

Thanks in advance and thanks for providing us with such useful library!
Caio

**Comment by peterpeterparker** [comment]
I think you are hitting a known limitation, see [README](https://github.com/peterpeterparker/web-photo-filter#limitation).

If you reduce the number of thumbnails, do you hit the issue too?

**Comment by caio1985** [comment]
Got point, if I reduce the number of filters the problem does not happen.

I'm using Ionic with capacitor. On browser it works up to 10 thumbnails.
When I build it to Android (10 thumbnails) it fails.

I reduced to 5 then Android is able to load all thumbnails. I will keep 5 as the sweet spot.

Now, if I need to load more how should I handle this in my code so I don't run into the problem again? Any suggestions (ie. removing the HTML element and adding it again) I don't know how I would be able to clean the GL contexts opened by the previous 5 instances.

**Comment by peterpeterparker** [comment]
Thanks for the check and feedback, therefore I gonna close the issue not much I can do.
Of course if you find a way to improve the component you are most welcome to submit a PR.

Regarding your last question, few years ago when I implemented the component I did no tried to find alternative, I just went with less filters on android. One spontaneous idea of solution would be to not use the component for each filters but rather to use the component to generate the filter thumbnails and keep the outcome as image in memory. Then using these as button rather than each time the component. Not sure it can be done, not sure how, just a spontaneous idea. Hope you will find something, good luck 🤞
