### ISSUE TITLE
version ^2.0.0 no display angular 5 and ionic-angular 3.9.2

### ISSUE THREAD

**Issue by izakblom** [peterpeterparker/web-photo-filter#8]
The filters for version ^2.0.0 are not displayed in an Ionic 3 app. Is it supposed to be compatible?
Angular 5 and ionic-angular 3.9.2

Filters used as follows:
`<web-photo-filter 
                  [src]='somebase64Image'
                  (click)="applyFilter('')"
                  [filter]='filterStringEgSepia'
                  (filterLoad)="filterLoaded($event)">
</web-photo-filter>`

**Comment by peterpeterparker** [comment]
I don't know if it's compatible actually, I didn't tried after having updated it for Ionic v4 ;)

https://github.com/fluster/web-photo-filter/blob/master/CHANGELOG.md

What's for sure is that the version v1.1.1 of this filter is compatible with Ionic v3

You could follow the tutorial to install https://ionicacademy.com/ionic-image-filter-webgl/ just specify the version when you install it

     npm install web-photo-filter@1.1.1

**Comment by izakblom** [comment]
Okay. I was hoping the newer versions would work, because I have tried v1.1.1 and it does work on Ionic 3, but loading more than one filter at the same time causes crashes on iOS, seems like the Canvas elements take up too much memory. I was hoping the newer versions won't behave the same way. 

Any chance for future compatibility of v2.0.0^ with Ionic 3?

**Comment by peterpeterparker** [comment]
@izakblom you never know but I use to use v1.1.1 in my Ionic 3 app where I was loading one big filter and around 10 thumbnails filters in the same page on iOS (iPhone >= v6) without any problems

Also I'm surprised you says it crashes because if too much memory is consumed actually i would "just" I think not render anything but should not crash

You could also try the following page, it works on iOS https://webphotofilter.com

If you are able to reproduce your problem with a minimal app, open another issue and link your repo, I could try to find a bit of time to have a look
